// Generated by CoffeeScript 1.7.1
(function() {
  $('.sq').each(function() {
    var sq;
    sq = $(this);
    return sq.css('height', sq.css('width').replace('px', '') / sq.parent().css('height').replace('px', '') * 100 + '%');
  });

}).call(this);
